{%set name = "snakebite" %}
{%set version = "2.11.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "085238b4944cb9c658ee62d5794de936ac3d0c337c504b2cc86424a205ae978a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [py3k]
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - protobuf >2.4.1
    - argparse  # [py26]

test:
  imports:
    - snakebite
    - snakebite.protobuf

about:
  home: http://github.com/spotify/snakebite
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Pure Python HDFS client'
  description: |
    Snakebite is a python library that provides a pure python HDFS client and
    a wrapper around Hadoops minicluster. The client uses protobuf for
    communicating with the NameNode and comes in the form of a library and a
    command line interface.
  doc_url: http://snakebite.readthedocs.org/en/latest/
  doc_source_url: https://github.com/spotify/snakebite/blob/master/doc/source/index.rst
  dev_url: https://github.com/spotify/snakebite

extra:
  recipe-maintainers:
    - pmlandwehr
