# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "N3o49zioJEdbgAAz7mMpsdpE7EyRnmlj4+2jIHgDULwfmNapC6L6e3e7jaTYgbqXsl9IMZsYaMBx8vsJlAgmvryrcEqzfaY9+6PrIwsMECATmyoeyb+dk4IFMhg3AYYYKyz2pBE/JHL+v2JZk3Ps4ZpqrBTCgGC/94JWWI3BuBqI3A4PrCqar5aK6NZoMrMJU2TS6/wPzIlxbKFkkwlX860Lgs+kXod4FJg8PZN76FZVYuE8rY4wAbHtowLW/pLr9+YZtDnWFPGr+LAnHqeKO15sFkFtl1Hngwpw7igi2hHBSPtXip/fH3DhAX2w7iVvgMrdo0Jog0tWR6p5bXy3lQH2632FUagZ6H7Qz46eqzgsrNxJAgE53APmxT+AQyETcdzqYxOns+s9cyI4CLXs+Prj9Gszi4K6V8TK1+KCj3huTp4RAWx/gdKo98c0VZNLxc/4Pf+pKvhABv5WKGNo6GRrgAW6EClifLkgAG33zESCV7z5N9Ff7OL+x4O7xFOpOTF/1eYWlYVmHzoPppxl/61wg81Aha0PIam4NftyJTQYS2rq3uE34cQ2loTFAiG/7/ELbHe8JHq/YMDWEvHh7B3EYIe3BCbVGTlAhJubvKsJTWx1eYHsk+cQrTu9Mn8M0weyQAMKq0ndii1Iy0PJys0EDIeAXCDN3ifNXt+nksE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
