travis:
  secure:
    BINSTAR_TOKEN: Mf6UEWYGJvTZ9he5KXwXWwc+b7E1tePjYhOGKHCA2Dfoq5RNvu1NCgbdb0wh8dGthqRb5sCUH8F1kerRTerr9ZaViAvGTHzyx7lr3Rp9k4dYNz5q2zvVQkt+RYcDYqLr6F9IiZ+euDwDL3OOTZ7BoSwozKGSd9Vtev33GDkX/rJmhNBSCvJr35X6PsH6DEQRqTAOGLypqFCNdCNEQuH7tpCiGi4d38abYGDZgXcdUykpiACGAnLOvVTTJiAPCBz5ljTaX9QQXlP8eCYC5l77yJgrPUhF1zOxqvDzv0Wz2S7eoNKEjZSALlhRRHiURiz9qKOvTzrsjW/1hCN8Ebz6lWBUnY/sdX4macBERJy7hKhpNUoX78OxE5bhBtI353XimbvwhDdYni3As8bVf2Fey7WUYa+sYbDZhp4QCZO41iYTj06BWevPyEL9WAT9xBSlzGsqmRHNX3Z1q8EUAl7Oh7aM7wemh47KxuxKdnvmqdEA6dGu4DzvR96Z5HcGksNcmKFT5TYXG5F7AeyXcy9QDwtgS4FXHMNMK4RYNvvEIPAcFxphojxW69XIKGNPkiS4lB8pYZHIPnR22cTFYtNf6S5x7r6IkzhroKMZPkRWDTHeldlcf1A+ZV6oqXh2pdA7vMK+W2cS8sRV5vbfkb/bjGOND3qvswlKCuYKMLuH3KQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
