travis:
  secure:
    BINSTAR_TOKEN: Sqg6FYUNHF20hF4T7AK9rcoNwjvqTMocGg7uN5b5fwbmRqVTpn+3qL4CakzpJJLSHiCZq1ft9xO7TV8vfCnVO3j4Iz4F0RR2l8Vc/dl0ud+nArgJm/niIqtsIOpPeNvyBBYB7AqW2ZgcHNBfhWmZdTq8Oo8a4Kb9pRkbc0McLYuHYWhKntRd8ezrmaSjAYkD1CTzJ6/ERMUl7eUD3xosFmcRCyjR4BpZCUQ3GnoKy4uIj8LK8J73VpYEYDCECsLvZgdX/5IxWWx6bOBG43tQE0X7JCex+7XnuyJDTHCWdHQNCPAu24Fq27EDS/RdsJqLcPxQLqsQOgvc16JZm9NUPO3kDdw2T4hbRl8kZRYRlh5D1vkE3oW7Rfhz69h3V7SV3iurUPbvwTZlTfXWJsIXQ2w9+kCe5etYaRhXIo2nTduXGa4xGYitWbPUhYmnJ7P+AYYdBR+flPlbwfH+x/h2DZ9i6Mw4j6aM/jMIlnNDeh+OPoehkI2FaA21OJRzj8AIHnxma8/ND3dqzfujPiVeh6AWOKy0Pu15BErbj66UI0h0wNNhfTfCH7OC7LWxRIDSIxf8MuCsMPfY8udmubRuQdhk5UCDln6CS61uipXvpCqAHavFSciI1a6pe7SpsUo7mZHE2eS9zBgq/wgwleQ6xfp8kir+7vUnD7dusl4t1Sg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
