travis:
  secure:
    BINSTAR_TOKEN: N3o49zioJEdbgAAz7mMpsdpE7EyRnmlj4+2jIHgDULwfmNapC6L6e3e7jaTYgbqXsl9IMZsYaMBx8vsJlAgmvryrcEqzfaY9+6PrIwsMECATmyoeyb+dk4IFMhg3AYYYKyz2pBE/JHL+v2JZk3Ps4ZpqrBTCgGC/94JWWI3BuBqI3A4PrCqar5aK6NZoMrMJU2TS6/wPzIlxbKFkkwlX860Lgs+kXod4FJg8PZN76FZVYuE8rY4wAbHtowLW/pLr9+YZtDnWFPGr+LAnHqeKO15sFkFtl1Hngwpw7igi2hHBSPtXip/fH3DhAX2w7iVvgMrdo0Jog0tWR6p5bXy3lQH2632FUagZ6H7Qz46eqzgsrNxJAgE53APmxT+AQyETcdzqYxOns+s9cyI4CLXs+Prj9Gszi4K6V8TK1+KCj3huTp4RAWx/gdKo98c0VZNLxc/4Pf+pKvhABv5WKGNo6GRrgAW6EClifLkgAG33zESCV7z5N9Ff7OL+x4O7xFOpOTF/1eYWlYVmHzoPppxl/61wg81Aha0PIam4NftyJTQYS2rq3uE34cQ2loTFAiG/7/ELbHe8JHq/YMDWEvHh7B3EYIe3BCbVGTlAhJubvKsJTWx1eYHsk+cQrTu9Mn8M0weyQAMKq0ndii1Iy0PJys0EDIeAXCDN3ifNXt+nksE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
